version: "3.8"

# --------------------------------------------------------------
# Basic PGAdmin v4 container
# - modify the environment variables to match your needs
# - you can also copy the content into the docker-compose.yml file
#   to include it in the same stack
# --------------------------------------------------------------

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
